language: node_js
node_js:
- stable
script:
- npm run travis
deploy:
  provider: npm
  skip_cleanup: true
  email: code+tuyapinpm@maxisom.me
  api_key:
    secure: MDQfKHTdZJWZnRs69lEExwx7wW7Q+BdLDLKK/LzOD2WHqcy4vZq45V5s8vhlrGh6zDWa6CLYWmiByYIyr+0YFujrvyaUddXVWzuEKrIYG0SX/JkMrAyRQd2GoZkXCS2/5wdO7c8N1Wm55t65QTytzFBK4QJgv60YTWN9g1jGHmhiUnCZ8wbDti9gN/aeUU+36F4tulB3SMtsuimACwWlpNbOpRGSyMn1HcbW85ta3V0xYRuSKCnHByQbHpB1NugHw7FNeJ/3k+6a115YNog2UeYN8kafEKbAQ9OsXosrgDPCBD6w11GFwfBhYsR4g1VxXK06btQqMpbUrRVZCLx4iWBTQmNr0bkCYKflm74+hcxd/VdlreyllHCMoha4cpkHOoWCzn+uk1pFQfI2cCFaINuzJCfXIYlNAYAVpJIKau1erfT3OA9696u20Uk0rBSyzEWSgFwhAeQZam5X1PPJtzIllx+8n1VDRw9fKMDjAj2HMb5MLlo9RZIScHDeeVQiJUNoJElDjXZzfBESsruOTcLQott6sJxFUCxepviZ8x/rkFF0JhQdvRSwDHKoLXRicgCoh2cJ+6JCeaur0LxWsP7qCDemimvc/8Ge3eeHuOJzq+gz4fzrECp3mV8RvM1p6mQY/NbxIdNivyMtRmjYk8pB/vNP/SFLbc7XycKsONM=
  on:
    tags: true
    repo: TuyaAPI/openapi
    branch: master
